/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author LENOVO
 */
public class DataBarang extends javax.swing.JDialog {

    /**
     * Creates new form DataBarang
     */
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    protected void DataTableBarang(){
        tabmode = (DefaultTableModel) tbldata.getModel();
        tbldata.setModel(tabmode);
        String sql = "select * from databarang";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery (sql);
            while (hasil.next()){
                String a = hasil.getString("kd_barang"); //isi tabel database
                String b = hasil.getString("nm_barang");
                String c = hasil.getString("kategori");
                String d = hasil.getString("hrg_beli");
                String e = hasil.getString("hrg_jual");
                String f = hasil.getString("jumlah");
                
 
                String[]data = {a,b,c,d,e,f};
                tabmode.addRow(data);
                System.out.println(sql);
            }
        } catch (Exception e){
        }
    }
    
    public static int data;
    public static String kode,barang,hrg,hrga;
    
    public DataBarang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DataTableBarang();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        txtbarang = new javax.swing.JLabel();
        txtcaribarang = new javax.swing.JTextField();
        txtbarang1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(64, 186, 213));
        jPanel1.setPreferredSize(new java.awt.Dimension(442, 305));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        tbldata.setBackground(new java.awt.Color(64, 186, 213));
        tbldata.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Kategori", "Harga Beli", "Harga Jual", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldata.setGridColor(new java.awt.Color(64, 186, 213));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldata);

        txtbarang.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtbarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Search_18px.png"))); // NOI18N

        txtcaribarang.setBackground(new java.awt.Color(255, 255, 255));
        txtcaribarang.setForeground(new java.awt.Color(0, 0, 0));
        txtcaribarang.setBorder(null);
        txtcaribarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcaribarangKeyReleased(evt);
            }
        });

        txtbarang1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtbarang1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbarang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Batal.png"))); // NOI18N
        txtbarang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbarang1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcaribarang, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcaribarang)
                    .addComponent(txtbarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtbarang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        if(evt.getClickCount() == 2 && !evt.isConsumed()) {
            data = tbldata.getSelectedRow();
            kode = tabmode.getValueAt(data, 0).toString();
            barang = tabmode.getValueAt(data, 1).toString();
            hrg = tabmode.getValueAt(data, 3).toString();
            hrga = tabmode.getValueAt(data, 4).toString();
            this.dispose();
        }
    }//GEN-LAST:event_tbldataMouseClicked

    private void txtcaribarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaribarangKeyReleased
        tabmode = (DefaultTableModel) tbldata.getModel();
        tbldata.setModel(tabmode);
        String sql = "SELECT * FROM databarang WHERE kd_barang LIKE '%"+txtcaribarang.getText()+"%'"
        + "OR nm_barang like '%"+txtcaribarang.getText()+"%'"
        + "OR kategori like '%"+txtcaribarang.getText()+"%'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String a = hasil.getString("kd_barang");
                String b = hasil.getString("nm_barang");
                String c = hasil.getString("kategori");
                String d = hasil.getString("hrg_beli");
                String e = hasil.getString("hrg_jual");
                String f = hasil.getString("jumlah");
                
                String [] data = {a,b,c,d,e,f};
                tabmode.addRow(data);
            }
        }catch (Exception e){
        }
    }//GEN-LAST:event_txtcaribarangKeyReleased

    private void txtbarang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbarang1MouseClicked
        this.dispose();
    }//GEN-LAST:event_txtbarang1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DataBarang dialog = new DataBarang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbldata;
    private javax.swing.JLabel txtbarang;
    private javax.swing.JLabel txtbarang1;
    private javax.swing.JTextField txtcaribarang;
    // End of variables declaration//GEN-END:variables
}
