package tampilan;

import java.awt.Color;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;


public class Data_Pemasok extends javax.swing.JFrame {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public Map param = new HashMap();
    
    protected void DataTable(){
        Object[] baris = {"ID Pemasok","Nama","Alamat","No.Telepon"};
        tabmode = new DefaultTableModel(null,baris);
        tblpemasok.setModel(tabmode);
        String sql = "select * from datapemasok";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery (sql);
            while (hasil.next()){
                String a = hasil.getString("id_pemasok"); //isi tabel database
                String b = hasil.getString("nm_pemasok");
                String c = hasil.getString("alamat");
                String d = hasil.getString("notelp");
 
                String[]data = {a,b,c,d};
                tabmode.addRow(data);
            }
        } catch (Exception e){
        }
    }
    
    public void kodepemasok(){
        try{
            String sql = "select id_pemasok from datapemasok order by id_pemasok desc";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(sql);
                if(rs.next()){
                    String kode = rs.getString("id_pemasok").substring(2);
                    String AN = ""+(Integer.parseInt(kode)+1);
                    String Nol = "";
                    
                    if(AN.length()==1){
                        Nol="000";
                    }else if(AN.length()==2){
                        Nol="00";
                    }else if(AN.length()==3){
                        Nol="0";
                     }else if(AN.length()==4){
                        Nol="";
                     }
                    txtid.setText("ID" + Nol + AN);
                }else{
                    txtid.setText("ID0001");
                }   
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    protected void kosong() {
        txtnama.setText("");
        txtalamat.setText("");
        txttelepon.setText("");
        kodepemasok();

    }
    
    public void batal(){
        tambah.setBackground(new Color(18,1,54));
        batal.setBackground(new Color(18,1,54));
        ubah.setBackground(new Color(18,1,54));
        batal1.setBackground(new Color(18,1,54));
        batal.setOpaque(false);
        tambah.setOpaque(false);
        ubah.setOpaque(false);
        batal1.setOpaque(false);
    }
    
    public Data_Pemasok() {
        initComponents();
        kodepemasok();
        DataTable();
        
        this.setLocationRelativeTo(null);
        batal();
        Data.setVisible(false);
        btubah.setVisible(false);
        Locale l = new Locale("id","ID");
        Locale.setDefault(l);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        batal = new javax.swing.JLabel();
        batal1 = new javax.swing.JLabel();
        tambah = new javax.swing.JLabel();
        ubah = new javax.swing.JLabel();
        hapus = new javax.swing.JLabel();
        beranda = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        tabel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpemasok = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Data = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblkd = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        lblalamat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        txtnama = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        lbltelpon = new javax.swing.JLabel();
        txttelepon = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        data = new javax.swing.JMenu();
        barang = new javax.swing.JMenuItem();
        pemasok = new javax.swing.JMenuItem();
        karyawan = new javax.swing.JMenuItem();
        transakso = new javax.swing.JMenu();
        jual = new javax.swing.JMenuItem();
        beli = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        dBarang = new javax.swing.JMenuItem();
        dKaryawan = new javax.swing.JMenuItem();
        dPelanggan = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        tBeli = new javax.swing.JMenuItem();
        tJual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Pemasok");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(27, 152, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        batal.setBackground(new java.awt.Color(255, 255, 255));
        batal.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        batal.setForeground(new java.awt.Color(255, 255, 255));
        batal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batalMouseClicked(evt);
            }
        });
        jPanel1.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 180, 5, 30));

        batal1.setBackground(new java.awt.Color(255, 255, 255));
        batal1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        batal1.setForeground(new java.awt.Color(255, 255, 255));
        batal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        batal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batal1MouseClicked(evt);
            }
        });
        jPanel1.add(batal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 240, 5, 30));

        tambah.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tambah.setText("TAMBAH DATA");
        tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });
        jPanel1.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 202, 30));

        ubah.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        ubah.setForeground(new java.awt.Color(255, 255, 255));
        ubah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ubah.setText("UBAH DATA");
        ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahMouseClicked(evt);
            }
        });
        jPanel1.add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 202, 30));

        hapus.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hapus.setText("HAPUS DATA");
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 200, 30));

        beranda.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 255));
        beranda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        beranda.setText("BERANDA");
        beranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaMouseClicked(evt);
            }
        });
        jPanel1.add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 200, 30));

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setLayout(new java.awt.CardLayout());

        tabel.setBackground(new java.awt.Color(64, 186, 213));
        tabel.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        tblpemasok.setAutoCreateRowSorter(true);
        tblpemasok.setBackground(new java.awt.Color(64, 186, 213));
        tblpemasok.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblpemasok.setForeground(new java.awt.Color(0, 0, 0));
        tblpemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Pemasok", "Nama", "Alamat", "No. Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblpemasok.setGridColor(new java.awt.Color(64, 186, 213));
        tblpemasok.setSelectionBackground(new java.awt.Color(18, 1, 54));
        tblpemasok.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblpemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpemasokMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblpemasok);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Search_18px.png"))); // NOI18N

        javax.swing.GroupLayout tabelLayout = new javax.swing.GroupLayout(tabel);
        tabel.setLayout(tabelLayout);
        tabelLayout.setHorizontalGroup(
            tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addGroup(tabelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabelLayout.setVerticalGroup(
            tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel.add(tabel, "card3");

        jPanel2.setBackground(new java.awt.Color(18, 1, 54));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblkd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblkd.setForeground(new java.awt.Color(255, 255, 255));
        lblkd.setText("ID Pemasok");
        jPanel2.add(lblkd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 22));

        lblnama.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblnama.setForeground(new java.awt.Color(255, 255, 255));
        lblnama.setText("Nama Pemasok");
        jPanel2.add(lblnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 22));

        lblalamat.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblalamat.setForeground(new java.awt.Color(255, 255, 255));
        lblalamat.setText("Alamat");
        jPanel2.add(lblalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 21));

        jScrollPane2.setBorder(null);

        txtalamat.setBackground(new java.awt.Color(255, 255, 255));
        txtalamat.setColumns(20);
        txtalamat.setForeground(new java.awt.Color(0, 0, 0));
        txtalamat.setRows(5);
        txtalamat.setBorder(null);
        txtalamat.setCaretColor(new java.awt.Color(51, 51, 51));
        jScrollPane2.setViewportView(txtalamat);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 330, -1));

        txtnama.setBackground(new java.awt.Color(255, 255, 255));
        txtnama.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtnama.setForeground(new java.awt.Color(51, 51, 51));
        txtnama.setBorder(null);
        jPanel2.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 22));

        txtid.setBackground(new java.awt.Color(255, 255, 255));
        txtid.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 0, 0));
        txtid.setBorder(null);
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, 22));

        lbltelpon.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbltelpon.setForeground(new java.awt.Color(255, 255, 255));
        lbltelpon.setText("No. Telepon");
        jPanel2.add(lbltelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 22));

        txttelepon.setBackground(new java.awt.Color(255, 255, 255));
        txttelepon.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txttelepon.setForeground(new java.awt.Color(0, 0, 0));
        txttelepon.setBorder(null);
        jPanel2.add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 180, 22));

        bttambah.setBackground(new java.awt.Color(255, 255, 255));
        bttambah.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });
        jPanel2.add(bttambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 90, 30));

        btbatal.setBackground(new java.awt.Color(255, 255, 255));
        btbatal.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btbatal.setText("Bersih");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });
        jPanel2.add(btbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 90, 30));

        btubah.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btubah.setText("Ubah");
        btubah.setPreferredSize(new java.awt.Dimension(74, 32));
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });
        jPanel2.add(btubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 90, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Batal.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel2FocusGained(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 30, 30));

        javax.swing.GroupLayout DataLayout = new javax.swing.GroupLayout(Data);
        Data.setLayout(DataLayout);
        DataLayout.setHorizontalGroup(
            DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataLayout.setVerticalGroup(
            DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
        );

        Panel.add(Data, "card3");

        jPanel1.add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 560, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/DataPemasok.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        data.setBackground(new java.awt.Color(0, 153, 204));
        data.setText("Data ");

        barang.setBackground(new java.awt.Color(255, 255, 255));
        barang.setText("Data Barang");
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        data.add(barang);

        pemasok.setBackground(new java.awt.Color(255, 255, 255));
        pemasok.setText("Data Pemasok");
        pemasok.setEnabled(false);
        pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasokActionPerformed(evt);
            }
        });
        data.add(pemasok);

        karyawan.setBackground(new java.awt.Color(255, 255, 255));
        karyawan.setText("Data Karyawan");
        karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanActionPerformed(evt);
            }
        });
        data.add(karyawan);

        jMenuBar1.add(data);

        transakso.setBackground(new java.awt.Color(0, 153, 204));
        transakso.setText("Transaksi");

        jual.setBackground(new java.awt.Color(255, 255, 255));
        jual.setText("Penjualan");
        jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jualActionPerformed(evt);
            }
        });
        transakso.add(jual);

        beli.setBackground(new java.awt.Color(255, 255, 255));
        beli.setText("Pembelian");
        beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliActionPerformed(evt);
            }
        });
        transakso.add(beli);

        jMenuBar1.add(transakso);

        jMenu2.setBackground(new java.awt.Color(0, 153, 204));
        jMenu2.setText("Laporan");

        jMenu3.setText("Data");

        dBarang.setText("Barang");
        dBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBarangActionPerformed(evt);
            }
        });
        jMenu3.add(dBarang);

        dKaryawan.setText("Karyawan");
        dKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dKaryawanActionPerformed(evt);
            }
        });
        jMenu3.add(dKaryawan);

        dPelanggan.setText("Pelanggan");
        dPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(dPelanggan);

        jMenu2.add(jMenu3);

        transaksi.setText("Transaksi");

        tBeli.setText("Beli");
        tBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBeliActionPerformed(evt);
            }
        });
        transaksi.add(tBeli);

        tJual.setText("Jual");
        tJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJualActionPerformed(evt);
            }
        });
        transaksi.add(tJual);

        jMenu2.add(transaksi);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
        String sql = "UPDATE datapemasok set nm_pemasok=?, alamat=?, notelp=? "
                + "WHERE id_pemasok='"+txtid.getText()+"' ";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnama.getText());
            stat.setString(2, txtalamat.getText());
            stat.setString(3, txttelepon.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            System.out.println(sql);
            kosong();
            txtnama.requestFocus();
            DataTable();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btubahActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        String sql = "insert into datapemasok values (?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtid.getText());
            stat.setString(2, txtnama.getText());
            stat.setString(3, txtalamat.getText());
            stat.setString(4, txttelepon.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

            DataTable();
            kosong();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }//GEN-LAST:event_bttambahActionPerformed

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        kosong();
    }//GEN-LAST:event_btbatalActionPerformed

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
        batal();
        
        tabel.setVisible(false);
        Data.setVisible(true);
        batal1.setVisible(false);
        btubah.setVisible(false);
        bttambah.setVisible(true);
        
        tambah.setBackground(new Color(41,57,80));
        batal.setBackground(new Color(255,255,255));
        tambah.setOpaque(true);
        batal.setOpaque(true);
                
    }//GEN-LAST:event_tambahMouseClicked

    private void batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batalMouseClicked
        
    }//GEN-LAST:event_batalMouseClicked

    private void ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahMouseClicked
        int bar = tblpemasok.getSelectedRow();
        if(bar < 0)
        {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data");
            Data.setVisible(false);
            tabel.setVisible(true);
            batal();
        }
        else{
                Data.setVisible(true);
                tabel.setVisible(false);
                bttambah.setVisible(false);
                btubah.setVisible(true);
                batal();
                
                ubah.setBackground(new Color(41,57,80));
                batal1.setBackground(new Color(255,255,255));
                ubah.setOpaque(true);
                batal1.setOpaque(true);
                }
        tblpemasok.clearSelection();
    }//GEN-LAST:event_ubahMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tblpemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpemasokMouseClicked
        int bar = tblpemasok.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        txtid.setText(a);
        txtnama.setText(b);
        txtalamat.setText(c);
        txttelepon.setText(d);
    }//GEN-LAST:event_tblpemasokMouseClicked

    private void batal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batal1MouseClicked
        batal1.setVisible(false);
        ubah.setVisible(true);
        tabel.setVisible(true);
        Data.setVisible(false);
    }//GEN-LAST:event_batal1MouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        int bar = tblpemasok.getSelectedRow();
        if(bar < 0)
        {
            tabel.setVisible(true);
            Data.setVisible(false);
            batal.setVisible(false);
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang ingin dihapus");
        }
        else{
            int ok = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if(ok==0){
                String sql = "DELETE FROM datapemasok WHERE id_pemasok='"+txtid.getText()+"'";
                try {
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    kosong();
                    txtnama.requestFocus();
                    DataTable();
                } catch (SQLException e){
                    JOptionPane.showMessageDialog(null, "Data Gagal Dihapus "+e);
                }
            } else {
            kosong();
            }
        }
        tblpemasok.clearSelection();
    }//GEN-LAST:event_hapusMouseClicked

    private void berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseClicked
        Menu a = new Menu();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_berandaMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        batal();
        Data.setVisible(false);
        tabel.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel2FocusGained
    }//GEN-LAST:event_jLabel2FocusGained

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
    }//GEN-LAST:event_jLabel2MouseReleased

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        Data_Barang db = new Data_Barang();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_barangActionPerformed

    private void pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasokActionPerformed
        Data_Pemasok dp = new Data_Pemasok();
        dp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pemasokActionPerformed

    private void karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanActionPerformed
        Data_Karyawan dk = new Data_Karyawan();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_karyawanActionPerformed

    private void jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jualActionPerformed
        Transaksi_Jual tj = new Transaksi_Jual();
        tj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jualActionPerformed

    private void beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliActionPerformed
        Transaksi_Beli tb = new Transaksi_Beli();
        tb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_beliActionPerformed

    private void dBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBarangActionPerformed
        try {
            File x = new File("src/Laporan/barang.jrxml");
            JasperReport y = JasperCompileManager.compileReport(x.getAbsolutePath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(y,param,conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Data Barang");
            jv.setVisible(true);
        }
        catch(Exception z) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Gagal Menampilkan Laporan"+z);
        }
    }//GEN-LAST:event_dBarangActionPerformed

    private void dKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dKaryawanActionPerformed
        try {
            File x = new File("src/Laporan/karyawan.jrxml");
            JasperReport y = JasperCompileManager.compileReport(x.getAbsolutePath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(y,param,conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Data Karyawan");
            jv.setVisible(true);
        }
        catch(Exception z) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Gagal Menampilkan Laporan"+z);
        }
    }//GEN-LAST:event_dKaryawanActionPerformed

    private void dPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dPelangganActionPerformed
        try {
            File x = new File("src/Laporan/pelanggan.jrxml");
            JasperReport y = JasperCompileManager.compileReport(x.getAbsolutePath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(y,param,conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Data Pelanggan");
            jv.setVisible(true);
        }
        catch(Exception z) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Gagal Menampilkan Laporan"+z);
        }
    }//GEN-LAST:event_dPelangganActionPerformed

    private void tBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBeliActionPerformed
        periode n = new periode();
        n.settransaksi("beli");
        n.setVisible(true);
    }//GEN-LAST:event_tBeliActionPerformed

    private void tJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJualActionPerformed
        periode n = new periode();
        n.settransaksi("jual");
        n.setVisible(true);
    }//GEN-LAST:event_tJualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutoritxtkdlookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Pemasok().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Data;
    private javax.swing.JPanel Panel;
    private javax.swing.JMenuItem barang;
    private javax.swing.JLabel batal;
    private javax.swing.JLabel batal1;
    private javax.swing.JMenuItem beli;
    private javax.swing.JLabel beranda;
    private javax.swing.JButton btbatal;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton btubah;
    private javax.swing.JMenuItem dBarang;
    private javax.swing.JMenuItem dKaryawan;
    private javax.swing.JMenuItem dPelanggan;
    private javax.swing.JMenu data;
    private javax.swing.JLabel hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem jual;
    private javax.swing.JMenuItem karyawan;
    private javax.swing.JLabel lblalamat;
    private javax.swing.JLabel lblkd;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lbltelpon;
    private javax.swing.JMenuItem pemasok;
    private javax.swing.JMenuItem tBeli;
    private javax.swing.JMenuItem tJual;
    private javax.swing.JPanel tabel;
    private javax.swing.JLabel tambah;
    private javax.swing.JTable tblpemasok;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenu transakso;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelepon;
    private javax.swing.JLabel ubah;
    // End of variables declaration//GEN-END:variables
}
