/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author LENOVO
 */
public class Data_Karyawan extends javax.swing.JFrame {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public Map param = new HashMap();
    
    protected void DataTable(){
        Object[] baris = {"ID Karyawan","Nama","No.Telepon","Alamat"};
        tabmode = new DefaultTableModel(null, baris);
        tbldata.setModel(tabmode);
        String sql = "select * from datakaryawan";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery (sql);
            while (hasil.next()){
                String a = hasil.getString("id_karyawan"); //isi tabel database
                String b = hasil.getString("nm_karyawan");
                String c = hasil.getString("notelp");
                String d = hasil.getString("alamat");
 
                String[]data = {a,b,c,d};
                tabmode.addRow(data);
            }
        } catch (Exception e){
        }
    }
    
    public void kodekaryawan(){
        try{
            String sql = "select id_karyawan from datakaryawan order by id_karyawan desc";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(sql);
                if(rs.next()){
                    String kode = rs.getString("id_karyawan").substring(2);
                    String AN = ""+(Integer.parseInt(kode)+1);
                    String Nol = "";
                    
                    if(AN.length()==1){
                        Nol="000";
                    }else if(AN.length()==2){
                        Nol="00";
                    }else if(AN.length()==3){
                        Nol="0";
                     }else if(AN.length()==4){
                        Nol="";
                     }
                    idKaryawan.setText("ID" + Nol + AN);
                }else{
                    idKaryawan.setText("ID0001");
                }   
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    protected void kosong() {
        nmKaryawan.setText("");
        noKaryawan.setText("");
        alamat.setText("");
    }
    public Data_Karyawan() {
        initComponents();
        DataTable();
        kodekaryawan();
        this.setLocationRelativeTo(null);
        Locale l = new Locale("id","ID");
        Locale.setDefault(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idKaryawan = new javax.swing.JTextField();
        nmKaryawan = new javax.swing.JTextField();
        noKaryawan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        PanelGambar = new javax.swing.JPanel();
        nm = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        almt = new javax.swing.JLabel();
        Amt = new javax.swing.JLabel();
        telp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btbatal = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        bttambah = new javax.swing.JButton();
        beranda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        BG = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        data = new javax.swing.JMenu();
        barang = new javax.swing.JMenuItem();
        pemasok = new javax.swing.JMenuItem();
        karyawan = new javax.swing.JMenuItem();
        transakso = new javax.swing.JMenu();
        jual = new javax.swing.JMenuItem();
        beli = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        dBarang = new javax.swing.JMenuItem();
        dKaryawan = new javax.swing.JMenuItem();
        dPelanggan = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        tBeli = new javax.swing.JMenuItem();
        tJual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(18, 1, 54));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        jLabel2.setPreferredSize(new java.awt.Dimension(68, 16));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Karyawan");
        jLabel3.setPreferredSize(new java.awt.Dimension(68, 16));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No. Telepon");
        jLabel1.setPreferredSize(new java.awt.Dimension(68, 16));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");
        jLabel4.setPreferredSize(new java.awt.Dimension(68, 16));

        idKaryawan.setBackground(new java.awt.Color(255, 255, 255));

        nmKaryawan.setBackground(new java.awt.Color(255, 255, 255));

        noKaryawan.setBackground(new java.awt.Color(255, 255, 255));

        alamat.setBackground(new java.awt.Color(255, 255, 255));
        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(idKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(noKaryawan))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56)
                            .addComponent(nmKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 114, 420, 230));

        PanelGambar.setBackground(new java.awt.Color(255, 255, 255));
        PanelGambar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        PanelGambar.setForeground(new java.awt.Color(0, 102, 204));
        PanelGambar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nm.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        nm.setForeground(new java.awt.Color(255, 255, 255));
        nm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nm.setText("Nama");
        PanelGambar.add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 150, 30));

        tel.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        tel.setForeground(new java.awt.Color(255, 255, 255));
        tel.setText("Telepon :");
        PanelGambar.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        almt.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        almt.setForeground(new java.awt.Color(255, 255, 255));
        almt.setText("Alamat   :  ");
        PanelGambar.add(almt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 60, -1));

        Amt.setForeground(new java.awt.Color(255, 255, 255));
        PanelGambar.add(Amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 130, 20));

        telp.setForeground(new java.awt.Color(255, 255, 255));
        PanelGambar.add(telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 130, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Card.png"))); // NOI18N
        PanelGambar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 376, 224));

        jPanel1.add(PanelGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 382, 230));

        jPanel3.setBackground(new java.awt.Color(18, 1, 54));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(18, 1, 54));

        btbatal.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btbatal.setText("Batal");
        btbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbatalActionPerformed(evt);
            }
        });

        btubah.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btubah.setText("Ubah");
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });

        bthapus.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bthapus.setText("Hapus");
        bthapus.setPreferredSize(new java.awt.Dimension(57, 28));
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        bttambah.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        beranda.setText("Beranda");
        beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bttambah, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(beranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btubah, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bthapus, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bthapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beranda)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 170, 160));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbldata.setBackground(new java.awt.Color(64, 186, 213));
        tbldata.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tbldata.setForeground(new java.awt.Color(0, 0, 0));
        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Karyawan", "Nama", "No, Telepon", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldata.setGridColor(new java.awt.Color(64, 186, 213));
        tbldata.setName(""); // NOI18N
        tbldata.setOpaque(false);
        tbldata.setSelectionBackground(new java.awt.Color(18, 1, 54));
        tbldata.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbldata);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 540, 140));

        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, 60));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/DataKaryawan.png"))); // NOI18N
        BG.setPreferredSize(new java.awt.Dimension(1035, 524));
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1035, 524));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        data.setBackground(new java.awt.Color(0, 153, 204));
        data.setText("Data ");

        barang.setBackground(new java.awt.Color(255, 255, 255));
        barang.setText("Data Barang");
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        data.add(barang);

        pemasok.setBackground(new java.awt.Color(255, 255, 255));
        pemasok.setText("Data Pemasok");
        pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasokActionPerformed(evt);
            }
        });
        data.add(pemasok);

        karyawan.setBackground(new java.awt.Color(255, 255, 255));
        karyawan.setText("Data Karyawan");
        karyawan.setEnabled(false);
        karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanActionPerformed(evt);
            }
        });
        data.add(karyawan);

        jMenuBar1.add(data);

        transakso.setBackground(new java.awt.Color(0, 153, 204));
        transakso.setText("Transaksi");

        jual.setBackground(new java.awt.Color(255, 255, 255));
        jual.setText("Penjualan");
        jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jualActionPerformed(evt);
            }
        });
        transakso.add(jual);

        beli.setBackground(new java.awt.Color(255, 255, 255));
        beli.setText("Pembelian");
        beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliActionPerformed(evt);
            }
        });
        transakso.add(beli);

        jMenuBar1.add(transakso);

        jMenu2.setBackground(new java.awt.Color(0, 153, 204));
        jMenu2.setText("Laporan");

        jMenu3.setText("Data");

        dBarang.setText("Barang");
        dBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBarangActionPerformed(evt);
            }
        });
        jMenu3.add(dBarang);

        dKaryawan.setText("Karyawan");
        dKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dKaryawanActionPerformed(evt);
            }
        });
        jMenu3.add(dKaryawan);

        dPelanggan.setText("Pelanggan");
        dPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(dPelanggan);

        jMenu2.add(jMenu3);

        transaksi.setText("Transaksi");

        tBeli.setText("Beli");
        tBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBeliActionPerformed(evt);
            }
        });
        transaksi.add(tBeli);

        tJual.setText("Jual");
        tJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJualActionPerformed(evt);
            }
        });
        transaksi.add(tJual);

        jMenu2.add(transaksi);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbatalActionPerformed
        kosong();
    }//GEN-LAST:event_btbatalActionPerformed

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
        String sql = "update datakaryawan set nm_karyawan=?, notelp=?, alamat=?,"
        + " where id_karyawan='"+idKaryawan.getText()+"'";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, nmKaryawan.getText());
            stat.setString(2, noKaryawan.getText());
            stat.setString(3, alamat.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            nmKaryawan.requestFocus();
            DataTable();
            kodekaryawan();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }
    }//GEN-LAST:event_btubahActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data?",
            "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(ok==0){
            String sql = "delete from datakaryawan where id_karyawan='"+idKaryawan.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                nmKaryawan.requestFocus();
                DataTable();
                kodekaryawan();
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus "+e);
            }
        } else {
            kosong();
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
        String sql = "insert into datakaryawan values (?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, idKaryawan.getText());
            stat.setString(2, nmKaryawan.getText());
            stat.setString(3, noKaryawan.getText());
            stat.setString(4, alamat.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

            DataTable();
            kodekaryawan();
            nmKaryawan.requestFocus();
            kosong();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
    }//GEN-LAST:event_bttambahActionPerformed

    private void berandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_berandaActionPerformed

    private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataMouseClicked
        int bar = tbldata.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        idKaryawan.setText(a);
        nmKaryawan.setText(b);
        noKaryawan.setText(c);
        alamat.setText(d);
        nm.setText(b);
        telp.setText(c);
        Amt.setText(d);
    }//GEN-LAST:event_tbldataMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        Data_Barang db = new Data_Barang();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_barangActionPerformed

    private void pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasokActionPerformed
        Data_Pemasok dp = new Data_Pemasok();
        dp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pemasokActionPerformed

    private void karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanActionPerformed
        Data_Karyawan dk = new Data_Karyawan();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_karyawanActionPerformed

    private void jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jualActionPerformed
        Transaksi_Jual tj = new Transaksi_Jual();
        tj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jualActionPerformed

    private void beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliActionPerformed
        Transaksi_Beli tb = new Transaksi_Beli();
        tb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_beliActionPerformed

    private void dBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBarangActionPerformed
        try {
            File x = new File("src/Laporan/barang.jrxml");
            JasperReport y = JasperCompileManager.compileReport(x.getAbsolutePath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(y,param,conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Data Barang");
            jv.setVisible(true);
        }
        catch(Exception z) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Gagal Menampilkan Laporan"+z);
        }
    }//GEN-LAST:event_dBarangActionPerformed

    private void dKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dKaryawanActionPerformed
        try {
            File x = new File("src/Laporan/karyawan.jrxml");
            JasperReport y = JasperCompileManager.compileReport(x.getAbsolutePath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(y,param,conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Data Karyawan");
            jv.setVisible(true);
        }
        catch(Exception z) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Gagal Menampilkan Laporan"+z);
        }
    }//GEN-LAST:event_dKaryawanActionPerformed

    private void dPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dPelangganActionPerformed
        try {
            File x = new File("src/Laporan/pelanggan.jrxml");
            JasperReport y = JasperCompileManager.compileReport(x.getAbsolutePath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(y,param,conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Data Pelanggan");
            jv.setVisible(true);
        }
        catch(Exception z) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Gagal Menampilkan Laporan"+z);
        }
    }//GEN-LAST:event_dPelangganActionPerformed

    private void tBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBeliActionPerformed
        periode n = new periode();
        n.settransaksi("beli");
        n.setVisible(true);
    }//GEN-LAST:event_tBeliActionPerformed

    private void tJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJualActionPerformed
        periode n = new periode();
        n.settransaksi("jual");
        n.setVisible(true);
    }//GEN-LAST:event_tJualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amt;
    private javax.swing.JLabel BG;
    private javax.swing.JPanel PanelGambar;
    private javax.swing.JTextArea alamat;
    private javax.swing.JLabel almt;
    private javax.swing.JMenuItem barang;
    private javax.swing.JMenuItem beli;
    private javax.swing.JButton beranda;
    private javax.swing.JButton btbatal;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton btubah;
    private javax.swing.JMenuItem dBarang;
    private javax.swing.JMenuItem dKaryawan;
    private javax.swing.JMenuItem dPelanggan;
    private javax.swing.JMenu data;
    private javax.swing.JTextField idKaryawan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jual;
    private javax.swing.JMenuItem karyawan;
    private javax.swing.JLabel nm;
    private javax.swing.JTextField nmKaryawan;
    private javax.swing.JTextField noKaryawan;
    private javax.swing.JMenuItem pemasok;
    private javax.swing.JMenuItem tBeli;
    private javax.swing.JMenuItem tJual;
    private javax.swing.JTable tbldata;
    private javax.swing.JLabel tel;
    private javax.swing.JLabel telp;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenu transakso;
    // End of variables declaration//GEN-END:variables
}
