/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author LENOVO
 */
public class DataPemasok extends javax.swing.JDialog {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    protected void DataTablePemasok(){
        //Object[] baris = {"ID Pemasok","Nama","Alamat","No.Telepon"};
        tabmode = (DefaultTableModel) tblpemasok.getModel();
        tblpemasok.setModel(tabmode);
        String sql = "SELECT * from datapemasok";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery (sql);
            while (hasil.next()){
                String a = hasil.getString("id_pemasok"); //isi tabel database
                String b = hasil.getString("nm_pemasok");
                String c = hasil.getString("alamat");
                String d = hasil.getString("notelp");
 
                String[]data = {a,b,c,d};
                tabmode.addRow(data);
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    
    public static int data;
    public static String id,nama;
    
    public DataPemasok(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DataTablePemasok();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtpemasok = new javax.swing.JLabel();
        txtcaripemasok = new javax.swing.JTextField();
        txtpemasok1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpemasok = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(64, 186, 213));
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(64, 186, 213));
        jPanel1.setPreferredSize(new java.awt.Dimension(442, 305));

        txtpemasok.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtpemasok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtpemasok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_Search_18px.png"))); // NOI18N

        txtcaripemasok.setBackground(new java.awt.Color(255, 255, 255));
        txtcaripemasok.setForeground(new java.awt.Color(0, 0, 0));
        txtcaripemasok.setBorder(null);
        txtcaripemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaripemasokActionPerformed(evt);
            }
        });
        txtcaripemasok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcaripemasokKeyReleased(evt);
            }
        });

        txtpemasok1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtpemasok1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtpemasok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Icon Batal.png"))); // NOI18N
        txtpemasok1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpemasok1MouseClicked(evt);
            }
        });

        tblpemasok.setBackground(new java.awt.Color(64, 186, 213));
        tblpemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pemasok", "Nama", "Alamat", "No. Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblpemasok.setGridColor(new java.awt.Color(64, 186, 213));
        tblpemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpemasokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpemasok);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtpemasok)
                        .addGap(12, 12, 12)
                        .addComponent(txtcaripemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(txtpemasok1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpemasok1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtpemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcaripemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcaripemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaripemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaripemasokActionPerformed

    private void txtcaripemasokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaripemasokKeyReleased
        tabmode = (DefaultTableModel) tblpemasok.getModel();
        tblpemasok.setModel(tabmode);
        String sql = "select * from datapemasok where id_pemasok like '%"+txtcaripemasok.getText()+"%'"
        + "or nm_pemasok like '%"+txtcaripemasok.getText()+"%'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String a = hasil.getString("id_pemasok");
                String b = hasil.getString("nm_pemasok");
                String [] data = {a,b};
                tabmode.addRow(data);
            }
        }catch (Exception e){
        }
    }//GEN-LAST:event_txtcaripemasokKeyReleased

    private void txtpemasok1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpemasok1MouseClicked
        this.dispose();
    }//GEN-LAST:event_txtpemasok1MouseClicked

    private void tblpemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpemasokMouseClicked
        if(evt.getClickCount() == 2 && !evt.isConsumed()) {
            data = tblpemasok.getSelectedRow();
            id = tabmode.getValueAt(data, 0).toString();
            nama = tabmode.getValueAt(data, 1).toString();
            this.dispose();
        }
    }//GEN-LAST:event_tblpemasokMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DataPemasok dialog = new DataPemasok(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpemasok;
    private javax.swing.JTextField txtcaripemasok;
    private javax.swing.JLabel txtpemasok;
    private javax.swing.JLabel txtpemasok1;
    // End of variables declaration//GEN-END:variables
}
