package tampilan;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import koneksi.koneksi;


public class fromlogin1 extends javax.swing.JFrame {

    koneksi a;
    int dragxmouse;
    int dragymouse;
    
    public fromlogin1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
    }
                                

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        lpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(680, 566));
        getContentPane().setLayout(null);

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(590, 30, 50, 40);

        user.setBackground(new java.awt.Color(0, 0, 0));
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setBorder(null);
        user.setCaretColor(new java.awt.Color(255, 255, 255));
        user.setOpaque(false);
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(140, 230, 310, 70);

        lpass.setBackground(new java.awt.Color(0, 0, 0));
        lpass.setForeground(new java.awt.Color(255, 255, 255));
        lpass.setBorder(null);
        lpass.setCaretColor(new java.awt.Color(255, 255, 255));
        lpass.setOpaque(false);
        lpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lpassKeyPressed(evt);
            }
        });
        getContentPane().add(lpass);
        lpass.setBounds(140, 330, 320, 60);

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 420, 420, 70);

        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 660, 550);

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/fromlogin.jpg"))); // NOI18N
        getContentPane().add(gambar);
        gambar.setBounds(0, 0, 680, 570);

        setSize(new java.awt.Dimension(677, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse,y - dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/aksesoris","root","");
            ResultSet as = con.createStatement().executeQuery("select * from login where uname ='"
                    +user.getText()+"' and pass='"+String.valueOf(lpass.getText()+"'"));
                if(as.next()){
                    javax.swing.JOptionPane.showMessageDialog(null,"Login sukses","Info",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    Menu m = new Menu();
                    m.setVisible(true);
                    this.dispose();
                }else
                javax.swing.JOptionPane.showMessageDialog(null,"Username tidak dikenal","Info",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                user.setText("");
                lpass.setText("");
                user.requestFocus();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER) {
            lpass.requestFocus();
        }
    }//GEN-LAST:event_userKeyPressed

    private void lpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lpassKeyPressed
         if(evt.getKeyCode()==evt.VK_ENTER) {
            if(user.getText().equals("admin") &&
                lpass.getText().equals("admin")) {
                javax.swing.JOptionPane.showMessageDialog(null,
                    "Anda berhasil masuk",
                    "Konfirmasi",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                new Menu().setVisible(true);
                dispose();
            }
            else {
                javax.swing.JOptionPane.showMessageDialog(null,
                    "User anda tidak dikenal",
                    "Kesalahan",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                user.setText("");
                lpass.requestFocus();
            }
        }
    }//GEN-LAST:event_lpassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromlogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromlogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromlogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromlogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromlogin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel gambar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField lpass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
