/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ILYAS
 */
public class Menu extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    public Map param = new HashMap();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        Locale l = new Locale("id","ID");
        Locale.setDefault(l);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        data = new javax.swing.JMenu();
        barang = new javax.swing.JMenuItem();
        pemasok = new javax.swing.JMenuItem();
        karyawan = new javax.swing.JMenuItem();
        transakso = new javax.swing.JMenu();
        jual = new javax.swing.JMenuItem();
        beli = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        dBarang = new javax.swing.JMenuItem();
        dKaryawan = new javax.swing.JMenuItem();
        dPelanggan = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        tBeli = new javax.swing.JMenuItem();
        tJual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 720));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Menu.jpg"))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        data.setBackground(new java.awt.Color(0, 153, 204));
        data.setText("Data ");

        barang.setBackground(new java.awt.Color(255, 255, 255));
        barang.setText("Data Barang");
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });
        data.add(barang);

        pemasok.setBackground(new java.awt.Color(255, 255, 255));
        pemasok.setText("Data Pemasok");
        pemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemasokActionPerformed(evt);
            }
        });
        data.add(pemasok);

        karyawan.setText("Data Karyawan");
        karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanActionPerformed(evt);
            }
        });
        data.add(karyawan);

        jMenuBar1.add(data);

        transakso.setBackground(new java.awt.Color(0, 153, 204));
        transakso.setText("Transaksi");

        jual.setBackground(new java.awt.Color(255, 255, 255));
        jual.setText("Penjualan");
        jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jualActionPerformed(evt);
            }
        });
        transakso.add(jual);

        beli.setBackground(new java.awt.Color(255, 255, 255));
        beli.setText("Pembelian");
        beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliActionPerformed(evt);
            }
        });
        transakso.add(beli);

        jMenuBar1.add(transakso);

        jMenu2.setBackground(new java.awt.Color(0, 153, 204));
        jMenu2.setText("Laporan");

        jMenu3.setText("Data");

        dBarang.setText("Barang");
        dBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBarangActionPerformed(evt);
            }
        });
        jMenu3.add(dBarang);

        dKaryawan.setText("Karyawan");
        dKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dKaryawanActionPerformed(evt);
            }
        });
        jMenu3.add(dKaryawan);

        dPelanggan.setText("Pelanggan");
        dPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(dPelanggan);

        jMenu2.add(jMenu3);

        transaksi.setText("Transaksi");

        tBeli.setText("Beli");
        tBeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBeliMouseClicked(evt);
            }
        });
        tBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBeliActionPerformed(evt);
            }
        });
        transaksi.add(tBeli);

        tJual.setText("Jual");
        tJual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tJualMouseClicked(evt);
            }
        });
        tJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJualActionPerformed(evt);
            }
        });
        transaksi.add(tJual);

        jMenu2.add(transaksi);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        Data_Barang db = new Data_Barang();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_barangActionPerformed

    private void pemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemasokActionPerformed
        Data_Pemasok dp = new Data_Pemasok();
        dp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pemasokActionPerformed

    private void jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jualActionPerformed
        Transaksi_Jual tj = new Transaksi_Jual();
        tj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jualActionPerformed

    private void beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliActionPerformed
        Transaksi_Beli tb = new Transaksi_Beli();
        tb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_beliActionPerformed

    private void karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanActionPerformed
        Data_Karyawan dk = new Data_Karyawan();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_karyawanActionPerformed

    private void tBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBeliActionPerformed
        periode n = new periode();   
        n.settransaksi("beli");
        n.setVisible(true);
    }//GEN-LAST:event_tBeliActionPerformed

    private void tJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJualActionPerformed
        periode n = new periode();   
        n.settransaksi("jual");
        n.setVisible(true);
    }//GEN-LAST:event_tJualActionPerformed

    private void dBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBarangActionPerformed
        try {
            File x = new File("src/Laporan/barang.jrxml");
            JasperReport y = JasperCompileManager.compileReport(x.getAbsolutePath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(y,param,conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Data Barang");
            jv.setVisible(true);
        }
        catch(Exception z) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Gagal Menampilkan Laporan"+z);
        }
    }//GEN-LAST:event_dBarangActionPerformed

    private void dKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dKaryawanActionPerformed
        try {
            File x = new File("src/Laporan/karyawan.jrxml");
            JasperReport y = JasperCompileManager.compileReport(x.getAbsolutePath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(y,param,conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Data Karyawan");
            jv.setVisible(true);
        }
        catch(Exception z) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Gagal Menampilkan Laporan"+z);
        }
    }//GEN-LAST:event_dKaryawanActionPerformed

    private void dPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dPelangganActionPerformed
        try {
            File x = new File("src/Laporan/pelanggan.jrxml");
            JasperReport y = JasperCompileManager.compileReport(x.getAbsolutePath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(y,param,conn);
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Data Pelanggan");
            jv.setVisible(true);
        }
        catch(Exception z) {
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Gagal Menampilkan Laporan"+z);
        }
    }//GEN-LAST:event_dPelangganActionPerformed

    private void tBeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBeliMouseClicked
        periode n = new periode();   
        n.settransaksi("beli");
        n.setVisible(true);
    }//GEN-LAST:event_tBeliMouseClicked

    private void tJualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tJualMouseClicked
        periode n = new periode();   
        n.settransaksi("jual");
        n.setVisible(true);
    }//GEN-LAST:event_tJualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem barang;
    private javax.swing.JMenuItem beli;
    private javax.swing.JMenuItem dBarang;
    private javax.swing.JMenuItem dKaryawan;
    private javax.swing.JMenuItem dPelanggan;
    private javax.swing.JMenu data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jual;
    private javax.swing.JMenuItem karyawan;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem pemasok;
    private javax.swing.JMenuItem tBeli;
    private javax.swing.JMenuItem tJual;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenu transakso;
    // End of variables declaration//GEN-END:variables
}
